### ISSUE TITLE
[T1040] event created_date_time mismatch 에러

### ISSUE THREAD

**Issue by wooramy** [EncoredTech/OpenADR-Virtual-Top-Node#1]
# 이슈
Test 1040
- 두 개의 이벤트를 생성하고 publish 하는데
- 테스트 전에 같은 시각으로 db를 업데이트 해도 여전히 mismatch 가 남

# 원인 
- db 수정을 해도 업데이트가 되지 않는 건
  -  publish 할 때 이미 vens 테이블의 distribute_event_payload_text에 xml message가 들어가 있음
- 생성 시간이 아니라 업데이트 시간을 기준으로 생성시간이 정해짐
  - [관련 코드](https://github.com/EncoredTech/OpenADR-Virtual-Top-Node/blob/master/app/oadr/convert_event.rb#L243)

# 대안
1. 위 코드에서 updated_at 대신 created_at 쓰기
2. 테스트 실행시 publish 전에 db 값 수정 (애초에 minute으로 ceil 하면 값이 이미 같을 수도 있음)

**Comment by MincheolC** [comment]
#5 해결
